//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renamer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork.
        /// </summary>
        public static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Folders.
        /// </summary>
        public static string ArtworkFolders {
            get {
                return ResourceManager.GetString("ArtworkFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically select the best name match where no exact match is present.
        /// </summary>
        public static string AutoBestNameMapping {
            get {
                return ResourceManager.GetString("AutoBestNameMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically map games based on CRC values.
        /// </summary>
        public static string AutoCrcMapping {
            get {
                return ResourceManager.GetString("AutoCrcMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically map games where the name is an exact match (excluding ROM tags).
        /// </summary>
        public static string AutoExactNameMapping {
            get {
                return ResourceManager.GetString("AutoExactNameMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Name.
        /// </summary>
        public static string BestName {
            get {
                return ResourceManager.GetString("BestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        public static string Crc {
            get {
                return ResourceManager.GetString("Crc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform CRC check against MAME Softlist when renaming ROMs.
        /// </summary>
        public static string CrcCheck {
            get {
                return ResourceManager.GetString("CrcCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC does not match.
        /// </summary>
        public static string CrcNotMatched {
            get {
                return ResourceManager.GetString("CrcNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Name.
        /// </summary>
        public static string ExactName {
            get {
                return ResourceManager.GetString("ExactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        public static string FileInformation {
            get {
                return ResourceManager.GetString("FileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist: {0}.
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Failed To Rename:.
        /// </summary>
        public static string GamesFailedToRename {
            get {
                return ResourceManager.GetString("GamesFailedToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games In List:.
        /// </summary>
        public static string GamesInList {
            get {
                return ResourceManager.GetString("GamesInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Mapped:.
        /// </summary>
        public static string GamesMapped {
            get {
                return ResourceManager.GetString("GamesMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Not Mapped:.
        /// </summary>
        public static string GamesNotMapped {
            get {
                return ResourceManager.GetString("GamesNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Renamed Successfully:.
        /// </summary>
        public static string GamesRenamedSuccessfully {
            get {
                return ResourceManager.GetString("GamesRenamedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games With Missing Artwork:.
        /// </summary>
        public static string GamesWithMissingArtwork {
            get {
                return ResourceManager.GetString("GamesWithMissingArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the HyperSpin XML file. Are you sure it is valid?.
        /// </summary>
        public static string HyperSpinXmlError {
            get {
                return ResourceManager.GetString("HyperSpinXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperSpin XML File.
        /// </summary>
        public static string HyperSpinXmlFile {
            get {
                return ResourceManager.GetString("HyperSpinXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the MAME XML file. Are you sure it is valid?.
        /// </summary>
        public static string MameXmlError {
            get {
                return ResourceManager.GetString("MameXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAME Softlist XML File.
        /// </summary>
        public static string MameXmlFile {
            get {
                return ResourceManager.GetString("MameXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping data....
        /// </summary>
        public static string MappingData {
            get {
                return ResourceManager.GetString("MappingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Method.
        /// </summary>
        public static string MappingMethod {
            get {
                return ResourceManager.GetString("MappingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping {0} of {1}: {2}.
        /// </summary>
        public static string MappingProgress {
            get {
                return ResourceManager.GetString("MappingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map To.
        /// </summary>
        public static string MapTo {
            get {
                return ResourceManager.GetString("MapTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Artwork.
        /// </summary>
        public static string MissingArtwork {
            get {
                return ResourceManager.GetString("MissingArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Artwork: {0}.
        /// </summary>
        public static string MissingArtworkDetails {
            get {
                return ResourceManager.GetString("MissingArtworkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping selected.
        /// </summary>
        public static string NoMappingSelected {
            get {
                return ResourceManager.GetString("NoMappingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder is not empty. The existing contents will be deleted if you proceed. Do you wish to proceed?.
        /// </summary>
        public static string OutputFolderNotEmptyMessage {
            get {
                return ResourceManager.GetString("OutputFolderNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder Not Empty.
        /// </summary>
        public static string OutputFolderNotEmptyTitle {
            get {
                return ResourceManager.GetString("OutputFolderNotEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading HyperSpin Data.
        /// </summary>
        public static string ReadingHyperSpinData {
            get {
                return ResourceManager.GetString("ReadingHyperSpinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading MAME Data.
        /// </summary>
        public static string ReadingMameData {
            get {
                return ResourceManager.GetString("ReadingMameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming files....
        /// </summary>
        public static string RenamingFiles {
            get {
                return ResourceManager.GetString("RenamingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0} of {1}: {2}.
        /// </summary>
        public static string RenamingProgress {
            get {
                return ResourceManager.GetString("RenamingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM file not found.
        /// </summary>
        public static string RomFileNotFound {
            get {
                return ResourceManager.GetString("RomFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM Folder.
        /// </summary>
        public static string RomFolder {
            get {
                return ResourceManager.GetString("RomFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roms.
        /// </summary>
        public static string Roms {
            get {
                return ResourceManager.GetString("Roms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception has occurred..
        /// </summary>
        public static string UnhandledExceptionInstruction {
            get {
                return ResourceManager.GetString("UnhandledExceptionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        public static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
    }
}
